services:
  gem5:
    image: gem5_img_2_13
    container_name: gem5_container
    stdin_open: true
    tty: true
    command: /bin/bash
    volumes: - /home/retro/gem5_research:/workspace/gem5_research
