services:
  gem5:
    image: gem5_img_zsh:latest # points to image, will likely revise naming convention
    container_name: gem5_container
    stdin_open: true
    tty: true
    command: /bin/zsh  --login # start zsh
    volumes:
      - /home/retro/gem5_research:/workspace/gem5_research # mount gem5_research
    devices:
      - /dev/kvm:/dev/kvm  # Grants KVM access to the container
    privileged: true
